# Page Configurations
# Created in Oct 31, 2022
# version: 0.4	Nov 2, 2022 11:38 AM

# Theme 主題
theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0

# Title 標題
title: GSI Collection

# Description 描述
description: 通用系統映像合集

# Author 作者
author: lelenext

# 提供下载 URL
show_downloads: false
