# Page Configurations
# Created in Oct 31, 2022
# version: 0.4	Nov 2, 2022 11:38 AM

# Theme 主題
theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0

# Title 標題
title: Tested GSIs for Redmi Note 8 Pro

# Description 描述
description: Tested GSI Packages for codename begonia

# Author 作者
author: ios7jbpro & lelenext

# 提供下载 URL
show_downloads: false
