# Page Configurations
# Oct 31, 2022

# Theme 主題
theme: jekyll-theme-cayman

# Title 標題
title: GSI Collection

# Subtitle 副標題
subtitle: 通用系統映像合集

# Author 作者
author: lelenext

# Description 描述
# description: 就一收集站點有啥好描述的 :p
